[package]
name = "liu-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
tokio-tungstenite = "0.17.2"
futures-util = "0.3"
thiserror = "1.0"

[dependencies.tokio]
version = "1.20.1"
features = ["fs", "net", "io-std", "io-util", "macros", "rt-multi-thread", "sync", "signal","time"]