[server]
address = "0.0.0.0"
port = 8001
path = "/proxy/ws"
auth_tokens = ["123456"]
use_ssl = false
#ssl_cert_path = "./config/certs/localhost.crt"
#ssl_key_path = "./config/certs/localhost.key"
[client]
address = "127.0.0.1"
port = 8002
auth_token = "123456"
server_url = "ws://localhost:8001/proxy/ws"
max_idle_conns = 30
#server_ip = "127.0.0.1"
#insecure = false