[server]
address = "0.0.0.0"
port = 8001
path = "/proxy/ws"
auth_tokens = ["123456"]
use_ssl = false
#ssl_cert_path = "./config/certs/localhost.crt"
#ssl_key_path = "./config/certs/localhost.key"
[client]
address = "127.0.0.1"
port = 8002
auth_token = "123456"
server_url = "ws://localhost:8001/proxy/ws"
max_idle_conns = 30
extra_http_headers = [
    [
        "User-Agent",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    ],
    [
        "Accept",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    ],
    [
        "Accept-Encoding",
        "gzip, deflate, br",
    ],
    [
        "Accept-Language",
        "zh-CN,zh;q=0.9",
    ],
    [
        "Cache-Control",
        "no-cache",
    ],
]
#server_ip = "127.0.0.1"
#insecure = false
