[client]
# 默认直连
default_action = "direct"
rules = [
    { action = "direct", selection = [
        "geosite:google@cn",
    ] },
    { action = "block", selection = [
        "geosite:category-ads-all",
        "domain:realsrv.com",
        "domain:playwrightglancing.com",
        "domain:in-page-push.com",
        "domain:juicyads.com",
        "domain:popads.net",
        "domain:chultoux.com",
        "domain:adxadserv.com"
    ] },
    { action = "proxy", selection = [
        "geosite:geolocation-!cn",
        "domain:aa.com",
    ] },
]
