[client]
# 域名默认直连
default_domain_action = "direct"
domain_rules = [
    { action = "direct", selection = [
        "geosite:google@cn",
        "geosite:steam@cn",
        "geosite:epicgames@cn",
    ] },
    { action = "block", selection = [
        "geosite:category-ads-all",
        "domain:realsrv.com",
        "domain:playwrightglancing.com",
        "domain:in-page-push.com",
        "domain:juicyads.com",
        "domain:popads.net",
        "domain:chultoux.com",
        "domain:adxadserv.com",
        "domain:report.url.cn",
    ] },
    { action = "proxy", selection = [
        "geosite:rust",
        "geosite:v2ray",
        "geosite:google",
        "geosite:github",
        "geosite:twitter",
        "geosite:telegram",
        "geosite:z-library",
        "geosite:category-forums",
        "geosite:category-porn",
        "geosite:steam",
        "geosite:epicgames",
        "domain:hostloc.com",
        "domain:curl.se",
    ] },
]

# ip默认代理
default_ip_action = "proxy"
ip_rules = [
    { action = "direct", selection = [
        "geoip:private",
        "223.5.5.5/32",
        "geoip:cn",
    ] },
]
